// Date: 9/5/2015 1:15:59 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.mrburger.PowerArmorMod.item.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlasmaCasterUnique extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Bulb1;
    ModelRenderer Bulb2;
    ModelRenderer Bulb3;
    ModelRenderer Bulb_4;
    ModelRenderer Bulb_5;
    ModelRenderer Bulb_6;
    ModelRenderer BaseBack;
    ModelRenderer BasBottom;
    ModelRenderer bASEsIDE1;
    ModelRenderer bASEsIDE2;
    ModelRenderer hANDLEBASEFRONT;
    ModelRenderer Handle;
    ModelRenderer BlasterBit;
    ModelRenderer Rod;
    ModelRenderer EndBase1;
    ModelRenderer EndBase2;
    ModelRenderer EndBase3;
    ModelRenderer EndSpike1;
    ModelRenderer EndSpike2;
    ModelRenderer EndSpike3;
  
  public ModelPlasmaCasterUnique()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 90, 0);
      Base.addBox(0F, 0F, 0F, 13, 7, 6);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Bulb1 = new ModelRenderer(this, 0, 0);
      Bulb1.addBox(1F, 0.5F, -0.5F, 1, 1, 1);
      Bulb1.setRotationPoint(0F, 0F, 0F);
      Bulb1.setTextureSize(64, 32);
      Bulb1.mirror = true;
      setRotation(Bulb1, 0F, 0F, 0F);
      Bulb2 = new ModelRenderer(this, 0, 0);
      Bulb2.addBox(3.5F, 0.5F, -0.5F, 1, 1, 1);
      Bulb2.setRotationPoint(0F, 0F, 0F);
      Bulb2.setTextureSize(64, 32);
      Bulb2.mirror = true;
      setRotation(Bulb2, 0F, 0F, 0F);
      Bulb3 = new ModelRenderer(this, 0, 0);
      Bulb3.addBox(6F, 0.5F, -0.5F, 1, 1, 1);
      Bulb3.setRotationPoint(0F, 0F, 0F);
      Bulb3.setTextureSize(64, 32);
      Bulb3.mirror = true;
      setRotation(Bulb3, 0F, 0F, 0F);
      Bulb_4 = new ModelRenderer(this, 0, 0);
      Bulb_4.addBox(1F, 0.5F, 5.5F, 1, 1, 1);
      Bulb_4.setRotationPoint(0F, 0F, 0F);
      Bulb_4.setTextureSize(64, 32);
      Bulb_4.mirror = true;
      setRotation(Bulb_4, 0F, 0F, 0F);
      Bulb_5 = new ModelRenderer(this, 0, 0);
      Bulb_5.addBox(3.5F, 0.5F, 5.5F, 1, 1, 1);
      Bulb_5.setRotationPoint(0F, 0F, 0F);
      Bulb_5.setTextureSize(64, 32);
      Bulb_5.mirror = true;
      setRotation(Bulb_5, 0F, 0F, 0F);
      Bulb_6 = new ModelRenderer(this, 0, 0);
      Bulb_6.addBox(6F, 0.5F, 5.5F, 1, 1, 1);
      Bulb_6.setRotationPoint(0F, 0F, 0F);
      Bulb_6.setTextureSize(64, 32);
      Bulb_6.mirror = true;
      setRotation(Bulb_6, 0F, 0F, 0F);
      BaseBack = new ModelRenderer(this, 76, 0);
      BaseBack.addBox(-1F, 1F, 0F, 1, 6, 6);
      BaseBack.setRotationPoint(0F, 0F, 0F);
      BaseBack.setTextureSize(64, 32);
      BaseBack.mirror = true;
      setRotation(BaseBack, 0F, 0F, 0F);
      BasBottom = new ModelRenderer(this, 46, 0);
      BasBottom.addBox(1F, 6.5F, 1F, 11, 1, 4);
      BasBottom.setRotationPoint(0F, 0F, 0F);
      BasBottom.setTextureSize(64, 32);
      BasBottom.mirror = true;
      setRotation(BasBottom, 0F, 0F, 0F);
      bASEsIDE1 = new ModelRenderer(this, 52, 5);
      bASEsIDE1.addBox(0.5F, 2F, -0.7F, 11, 4, 1);
      bASEsIDE1.setRotationPoint(0F, 0F, 0F);
      bASEsIDE1.setTextureSize(64, 32);
      bASEsIDE1.mirror = true;
      setRotation(bASEsIDE1, 0F, 0F, 0F);
      bASEsIDE2 = new ModelRenderer(this, 52, 5);
      bASEsIDE2.addBox(0.5F, 2F, 5.7F, 11, 4, 1);
      bASEsIDE2.setRotationPoint(0F, 0F, 0F);
      bASEsIDE2.setTextureSize(64, 32);
      bASEsIDE2.mirror = true;
      setRotation(bASEsIDE2, 0F, 0F, 0F);
      hANDLEBASEFRONT = new ModelRenderer(this, 108, 13);
      hANDLEBASEFRONT.addBox(8F, -0.3F, -0.5F, 3, 3, 7);
      hANDLEBASEFRONT.setRotationPoint(0F, 0F, 0F);
      hANDLEBASEFRONT.setTextureSize(64, 32);
      hANDLEBASEFRONT.mirror = true;
      setRotation(hANDLEBASEFRONT, 0F, 0F, 0F);
      Handle = new ModelRenderer(this, 32, 0);
      Handle.addBox(1F, -5F, 2F, 2, 7, 2);
      Handle.setRotationPoint(0F, 0F, 0F);
      Handle.setTextureSize(64, 32);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0.3490659F);
      BlasterBit = new ModelRenderer(this, 20, 0);
      BlasterBit.addBox(12.7F, 1F, 0.5F, 1, 5, 5);
      BlasterBit.setRotationPoint(0F, 0F, 0F);
      BlasterBit.setTextureSize(64, 32);
      BlasterBit.mirror = true;
      setRotation(BlasterBit, 0F, 0F, 0F);
      Rod = new ModelRenderer(this, 19, 42);
      Rod.addBox(12F, 3F, 2.5F, 16, 1, 1);
      Rod.setRotationPoint(0F, 0F, 0F);
      Rod.setTextureSize(64, 32);
      Rod.mirror = true;
      setRotation(Rod, 0F, 0F, 0F);
      EndBase1 = new ModelRenderer(this, 0, 30);
      EndBase1.addBox(0F, -3F, 0F, 3, 3, 1);
      EndBase1.setRotationPoint(27F, 3F, 3.5F);
      EndBase1.setTextureSize(128, 64);
      EndBase1.mirror = true;
      setRotation(EndBase1, -2.094395F, 0F, 0F);
      EndBase2 = new ModelRenderer(this, 0, 30);
      EndBase2.addBox(0F, -3F, 0F, 3, 3, 1);
      EndBase2.setRotationPoint(27F, 3.9F, 3F);
      EndBase2.setTextureSize(128, 64);
      EndBase2.mirror = true;
      setRotation(EndBase2, 2.094395F, 0F, 0F);
      EndBase3 = new ModelRenderer(this, 0, 30);
      EndBase3.addBox(0F, -3F, 0F, 3, 3, 1);
      EndBase3.setRotationPoint(27F, 3F, 2.5F);
      EndBase3.setTextureSize(128, 64);
      EndBase3.mirror = true;
      setRotation(EndBase3, 0F, 0F, 0F);
      EndSpike1 = new ModelRenderer(this, 0, 40);
      EndSpike1.addBox(1F, -4F, 0F, 6, 2, 1);
      EndSpike1.setRotationPoint(27F, 3F, 3.5F);
      EndSpike1.setTextureSize(128, 64);
      EndSpike1.mirror = true;
      setRotation(EndSpike1, -2.094395F, 0F, 0F);
      EndSpike2 = new ModelRenderer(this, 0, 40);
      EndSpike2.addBox(1F, -4F, 0F, 6, 2, 1);
      EndSpike2.setRotationPoint(27F, 3.9F, 3F);
      EndSpike2.setTextureSize(128, 64);
      EndSpike2.mirror = true;
      setRotation(EndSpike2, 2.094395F, 0F, 0F);
      EndSpike3 = new ModelRenderer(this, 0, 40);
      EndSpike3.addBox(1F, -4F, 0F, 6, 2, 1);
      EndSpike3.setRotationPoint(27F, 3F, 2.5F);
      EndSpike3.setTextureSize(128, 64);
      EndSpike3.mirror = true;
      setRotation(EndSpike3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Bulb1.render(f5);
    Bulb2.render(f5);
    Bulb3.render(f5);
    Bulb_4.render(f5);
    Bulb_5.render(f5);
    Bulb_6.render(f5);
    BaseBack.render(f5);
    BasBottom.render(f5);
    bASEsIDE1.render(f5);
    bASEsIDE2.render(f5);
    hANDLEBASEFRONT.render(f5);
    Handle.render(f5);
    BlasterBit.render(f5);
    Rod.render(f5);
    EndBase1.render(f5);
    EndBase2.render(f5);
    EndBase3.render(f5);
    EndSpike1.render(f5);
    EndSpike2.render(f5);
    EndSpike3.render(f5);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void renderModel(float f5) {
    Base.render(f5);
    Bulb1.render(f5);
    Bulb2.render(f5);
    Bulb3.render(f5);
    Bulb_4.render(f5);
    Bulb_5.render(f5);
    Bulb_6.render(f5);
    BaseBack.render(f5);
    BasBottom.render(f5);
    bASEsIDE1.render(f5);
    bASEsIDE2.render(f5);
    hANDLEBASEFRONT.render(f5);
    Handle.render(f5);
    BlasterBit.render(f5);
    Rod.render(f5);
    EndBase1.render(f5);
    EndBase2.render(f5);
    EndBase3.render(f5);
    EndSpike1.render(f5);
    EndSpike2.render(f5);
    EndSpike3.render(f5);

  }
}
