// Date: 8/30/2015 8:46:58 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.mrburger.PowerArmorMod.item.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelT45DArmor extends ModelBiped
{
  //fields
    ModelRenderer HelmetBase;
    ModelRenderer RespBase;
    ModelRenderer Pipesfront;
    ModelRenderer PipesSide2;
    ModelRenderer PipesSide1;
    ModelRenderer Side2;
    ModelRenderer Side1;
    ModelRenderer Back1;
    ModelRenderer Top1;
    ModelRenderer HelmetBridge;
    ModelRenderer HelmetFront1;
    ModelRenderer HelmetFront2;
    ModelRenderer HelmetFront3;
    ModelRenderer Respirator;
    ModelRenderer Chestplatebase;
    ModelRenderer ChestplatePlate;
    ModelRenderer Plate2;
    ModelRenderer Plate1;
    ModelRenderer TankValve;
    ModelRenderer Tank1;
    ModelRenderer Tank2;
    ModelRenderer RightPad;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer LeftPad;
    ModelRenderer leftleg;
    ModelRenderer LeftKnee;
    ModelRenderer rightleg;
    ModelRenderer RightKnee;
  
  public ModelT45DArmor()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      HelmetBase = new ModelRenderer(this, 94, 34);
      HelmetBase.addBox(-4.5F, -8.5F, -4F, 9, 9, 8);
      HelmetBase.setRotationPoint(0F, 0F, 0F);
      HelmetBase.setTextureSize(128, 128);
      HelmetBase.mirror = true;
      setRotation(HelmetBase, 0F, 0F, 0F);
      RespBase = new ModelRenderer(this, 102, 0);
      RespBase.addBox(-3F, -5F, -4.8F, 6, 5, 1);
      RespBase.setRotationPoint(0F, 0F, 0F);
      RespBase.setTextureSize(128, 128);
      RespBase.mirror = true;
      setRotation(RespBase, 0.0174533F, 0F, 0F);
      Pipesfront = new ModelRenderer(this, 108, 10);
      Pipesfront.addBox(-5F, -2F, -4.9F, 10, 1, 0);
      Pipesfront.setRotationPoint(0F, 0F, 0F);
      Pipesfront.setTextureSize(128, 128);
      Pipesfront.mirror = true;
      setRotation(Pipesfront, 0F, 0F, 0F);
      PipesSide2 = new ModelRenderer(this, 116, 0);
      PipesSide2.addBox(-5F, -1F, -4.9F, 0, 1, 6);
      PipesSide2.setRotationPoint(0F, -1F, 0F);
      PipesSide2.setTextureSize(128, 128);
      PipesSide2.mirror = true;
      setRotation(PipesSide2, 0F, 0F, 0F);
      PipesSide1 = new ModelRenderer(this, 116, 0);
      PipesSide1.addBox(5F, -1F, -4.9F, 0, 1, 6);
      PipesSide1.setRotationPoint(0F, -1F, 0F);
      PipesSide1.setTextureSize(128, 128);
      PipesSide1.mirror = true;
      setRotation(PipesSide1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 114, 14);
      Side2.addBox(-5F, -7F, -2.5F, 1, 6, 6);
      Side2.setRotationPoint(0F, 0F, 0F);
      Side2.setTextureSize(128, 128);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Side1 = new ModelRenderer(this, 100, 14);
      Side1.addBox(4F, -7F, -2.5F, 1, 6, 6);
      Side1.setRotationPoint(0F, 0F, 0F);
      Side1.setTextureSize(128, 128);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Back1 = new ModelRenderer(this, 110, 51);
      Back1.addBox(-4F, -7F, 3.4F, 8, 7, 1);
      Back1.setRotationPoint(0F, 0F, 0F);
      Back1.setTextureSize(128, 128);
      Back1.mirror = true;
      setRotation(Back1, 0F, 0F, 0F);
      Top1 = new ModelRenderer(this, 98, 26);
      Top1.addBox(-4F, -9F, -3.5F, 8, 1, 7);
      Top1.setRotationPoint(0F, 0F, 0F);
      Top1.setTextureSize(128, 128);
      Top1.mirror = true;
      setRotation(Top1, 0F, 0F, 0F);
      HelmetBridge = new ModelRenderer(this, 92, 11);
      HelmetBridge.addBox(-1F, -6F, -4.5F, 2, 2, 1);
      HelmetBridge.setRotationPoint(0F, 0F, 0F);
      HelmetBridge.setTextureSize(128, 128);
      HelmetBridge.mirror = true;
      setRotation(HelmetBridge, 0F, 0F, 0F);
      HelmetFront1 = new ModelRenderer(this, 82, 0);
      HelmetFront1.addBox(-4F, -7F, -4.5F, 1, 7, 1);
      HelmetFront1.setRotationPoint(0F, 0F, 0F);
      HelmetFront1.setTextureSize(128, 128);
      HelmetFront1.mirror = true;
      setRotation(HelmetFront1, 0F, 0F, 0F);
      HelmetFront2 = new ModelRenderer(this, 78, 0);
      HelmetFront2.addBox(3F, -7F, -4.5F, 1, 7, 1);
      HelmetFront2.setRotationPoint(0F, 0F, 0F);
      HelmetFront2.setTextureSize(128, 128);
      HelmetFront2.mirror = true;
      setRotation(HelmetFront2, 0F, 0F, 0F);
      HelmetFront3 = new ModelRenderer(this, 74, 11);
      HelmetFront3.addBox(-4F, -7F, -4.5F, 8, 1, 1);
      HelmetFront3.setRotationPoint(0F, 0F, 0F);
      HelmetFront3.setTextureSize(128, 128);
      HelmetFront3.mirror = true;
      setRotation(HelmetFront3, 0F, 0F, 0F);
      Respirator = new ModelRenderer(this, 92, 27);
      Respirator.addBox(-1F, -2.7F, -5.2F, 2, 2, 1);
      Respirator.setRotationPoint(0F, 0F, 0F);
      Respirator.setTextureSize(128, 128);
      Respirator.mirror = true;
      setRotation(Respirator, 0F, 0F, 0F);
      Chestplatebase = new ModelRenderer(this, 0, 110);
      Chestplatebase.addBox(-4F, 0F, -2.8F, 8, 12, 6);
      Chestplatebase.setRotationPoint(0F, 0F, 0F);
      Chestplatebase.setTextureSize(128, 128);
      Chestplatebase.mirror = true;
      setRotation(Chestplatebase, 0F, 0F, 0F);
      ChestplatePlate = new ModelRenderer(this, 28, 122);
      ChestplatePlate.addBox(-3.5F, 1F, -3.6F, 7, 5, 1);
      ChestplatePlate.setRotationPoint(0F, 0F, 0F);
      ChestplatePlate.setTextureSize(128, 128);
      ChestplatePlate.mirror = true;
      setRotation(ChestplatePlate, 0F, 0F, 0F);
      Plate2 = new ModelRenderer(this, 28, 115);
      Plate2.addBox(2.8F, 1F, -3.2F, 1, 6, 1);
      Plate2.setRotationPoint(0F, 0F, 0F);
      Plate2.setTextureSize(128, 128);
      Plate2.mirror = true;
      setRotation(Plate2, 0F, 0F, 0F);
      Plate1 = new ModelRenderer(this, 32, 115);
      Plate1.addBox(-3.8F, 1F, -3.2F, 1, 6, 1);
      Plate1.setRotationPoint(0F, 0F, 0F);
      Plate1.setTextureSize(128, 128);
      Plate1.mirror = true;
      setRotation(Plate1, 0F, 0F, 0F);
      TankValve = new ModelRenderer(this, 0, 95);
      TankValve.addBox(-2.5F, 1F, 3.2F, 5, 4, 1);
      TankValve.setRotationPoint(0F, 0F, 0F);
      TankValve.setTextureSize(128, 128);
      TankValve.mirror = true;
      setRotation(TankValve, 0F, 0F, 0F);
      Tank1 = new ModelRenderer(this, 0, 100);
      Tank1.addBox(0.5F, 2F, 2F, 3, 8, 2);
      Tank1.setRotationPoint(0F, 0F, 0F);
      Tank1.setTextureSize(128, 128);
      Tank1.mirror = true;
      setRotation(Tank1, 0F, 0F, 0F);
      Tank2 = new ModelRenderer(this, 0, 100);
      Tank2.addBox(-3.5F, 2F, 2F, 3, 8, 2);
      Tank2.setRotationPoint(0F, 0F, 0F);
      Tank2.setTextureSize(128, 128);
      Tank2.mirror = true;
      setRotation(Tank2, 0F, 0F, 0F);
      RightPad = new ModelRenderer(this, 108, 106);
      RightPad.addBox(-3.2F, -2.6F, -2.5F, 5, 1, 5);
      RightPad.setRotationPoint(0F, 0F, 0F);
      RightPad.setTextureSize(128, 128);
      RightPad.mirror = true;
      setRotation(RightPad, 0F, 0F, -0.1745329F);
      rightarm = new ModelRenderer(this, 112, 112);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(0F, 0F, 0F);
      rightarm.setTextureSize(128, 128);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 92, 112);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(0F, 0F, 0F);
      leftarm.setTextureSize(128, 128);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      LeftPad = new ModelRenderer(this, 88, 106);
      LeftPad.addBox(-1.8F, -2.5F, -2.5F, 5, 1, 5);
      LeftPad.setRotationPoint(0F, 0F, 0F);
      LeftPad.setTextureSize(128, 128);
      LeftPad.mirror = true;
      setRotation(LeftPad, 0F, 0F, 0.1745329F);
      leftleg = new ModelRenderer(this, 44, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(0F, 0F, 0F);
      leftleg.setTextureSize(128, 128);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      LeftKnee = new ModelRenderer(this, 52, 11);
      LeftKnee.addBox(-1.5F, 4F, -2.3F, 3, 4, 1);
      LeftKnee.setRotationPoint(0F, 0F, 0F);
      LeftKnee.setTextureSize(128, 128);
      LeftKnee.mirror = true;
      setRotation(LeftKnee, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 27, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(0F, 0F, 0F);
      rightleg.setTextureSize(128, 128);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      RightKnee = new ModelRenderer(this, 35, 11);
      RightKnee.addBox(-1.5F, 4F, -2.3F, 3, 4, 1);
      RightKnee.setRotationPoint(0F, 0F, 0F);
      RightKnee.setTextureSize(128, 128);
      RightKnee.mirror = true;
      setRotation(RightKnee, 0F, 0F, 0F);

      this.bipedHead.cubeList.clear();
      this.bipedHead.addChild(HelmetBase);
      this.bipedHead.addChild(RespBase);
      this.bipedHead.addChild(Pipesfront);
      this.bipedHead.addChild(PipesSide1);
      this.bipedHead.addChild(PipesSide2);
      this.bipedHead.addChild(Side1);
      this.bipedHead.addChild(Side2);
      this.bipedHead.addChild(Back1);
      this.bipedHead.addChild(Top1);
      this.bipedHead.addChild(HelmetBridge);
      this.bipedHead.addChild(HelmetFront1);
      this.bipedHead.addChild(HelmetFront2);
      this.bipedHead.addChild(HelmetFront3);;
      this.bipedHead.addChild(Respirator);

      this.bipedBody.cubeList.clear();
      this.bipedBody.addChild(Chestplatebase);
      this.bipedBody.addChild(ChestplatePlate);
      this.bipedBody.addChild(Plate2);
      this.bipedBody.addChild(Plate1);
      this.bipedBody.addChild(TankValve);
      this.bipedBody.addChild(Tank1);
      this.bipedBody.addChild(Tank2);

      this.bipedLeftArm.cubeList.clear();
      this.bipedLeftArm.addChild(leftarm);
      this.bipedLeftArm.addChild(LeftPad);

      this.bipedRightArm.cubeList.clear();
      this.bipedRightArm.addChild(rightarm);
      this.bipedRightArm.addChild(RightPad);

      this.bipedLeftLeg.cubeList.clear();
      this.bipedLeftLeg.addChild(leftleg);
      this.bipedLeftLeg.addChild(LeftKnee);

      this.bipedRightLeg.cubeList.clear();
      this.bipedRightLeg.addChild(rightleg);
      this.bipedRightLeg.addChild(RightKnee);
  }

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
      setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    bipedBody.render(f5 * 1.7F);
      bipedHead.render(f5 * 1.5F);
      bipedLeftArm.render(f5*1.1F);
      bipedRightArm.render(f5*1.1F);
      bipedLeftLeg.render(f5*1.1F);
      bipedRightLeg.render(f5*1.1F);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
