// Date: 9/3/2015 8:50:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.mrburger.PowerArmorMod.item.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlasmaBolt extends ModelBase
{
  //fields
    ModelRenderer Center;
    ModelRenderer Top;
    ModelRenderer Bottom;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
  
  public ModelPlasmaBolt()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Center = new ModelRenderer(this, 28, 0);
      Center.addBox(0F, 0F, 0F, 1, 1, 1);
      Center.setRotationPoint(0F, 0F, 0F);
      Center.setTextureSize(32, 32);
      Center.mirror = true;
      setRotation(Center, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(-1F, 0F, -1F, 3, 0, 3);
      Top.setRotationPoint(0F, 0F, 0F);
      Top.setTextureSize(32, 32);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Bottom = new ModelRenderer(this, 0, 0);
      Bottom.addBox(-1F, 1F, -1F, 3, 0, 3);
      Bottom.setRotationPoint(0F, 0F, 0F);
      Bottom.setTextureSize(32, 32);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Side1 = new ModelRenderer(this, 17, 0);
      Side1.addBox(0F, -1F, -1F, 0, 3, 3);
      Side1.setRotationPoint(0F, 0F, 0F);
      Side1.setTextureSize(32, 32);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 17, 0);
      Side2.addBox(1F, -1F, -1F, 0, 3, 3);
      Side2.setRotationPoint(0F, 0F, 0F);
      Side2.setTextureSize(32, 32);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Side3 = new ModelRenderer(this, 17, 0);
      Side3.addBox(-1F, -1F, 0F, 3, 3, 0);
      Side3.setRotationPoint(0F, 0F, 0F);
      Side3.setTextureSize(32, 32);
      Side3.mirror = true;
      setRotation(Side3, 0F, 0F, 0F);
      Side4 = new ModelRenderer(this, 17, 0);
      Side4.addBox(-1F, -1F, 1F, 3, 3, 0);
      Side4.setRotationPoint(0F, 0F, 0F);
      Side4.setTextureSize(32, 32);
      Side4.mirror = true;
      setRotation(Side4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Center.render(f5);
    Top.render(f5);
    Bottom.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void renderModel(float f5) {
    Center.render(f5);
    Top.render(f5);
    Bottom.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
  }
}
