// Date: 9/4/2015 7:38:18 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.mrburger.PowerArmorMod.item.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlasmaCaster extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Bulb1;
    ModelRenderer Bulb2;
    ModelRenderer Bulb3;
    ModelRenderer Bulb_4;
    ModelRenderer Bulb_5;
    ModelRenderer Bulb_6;
    ModelRenderer BaseBack;
    ModelRenderer BasBottom;
    ModelRenderer bASEsIDE1;
    ModelRenderer bASEsIDE2;
    ModelRenderer hANDLEBASEFRONT;
    ModelRenderer Handle;
    ModelRenderer BlasterBit;
    ModelRenderer Rod;
    ModelRenderer RodEnd1;
    ModelRenderer RodTerminus2;
    ModelRenderer RodEnd3;
    ModelRenderer RodEnd2;
    ModelRenderer RodTerminus1;
    ModelRenderer RodTerminus3;
  
  public ModelPlasmaCaster()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 90, 0);
      Base.addBox(0F, 0F, 0F, 13, 7, 6);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Bulb1 = new ModelRenderer(this, 0, 0);
      Bulb1.addBox(1F, 0.5F, -0.5F, 1, 1, 1);
      Bulb1.setRotationPoint(0F, 0F, 0F);
      Bulb1.setTextureSize(64, 32);
      Bulb1.mirror = true;
      setRotation(Bulb1, 0F, 0F, 0F);
      Bulb2 = new ModelRenderer(this, 0, 0);
      Bulb2.addBox(3.5F, 0.5F, -0.5F, 1, 1, 1);
      Bulb2.setRotationPoint(0F, 0F, 0F);
      Bulb2.setTextureSize(64, 32);
      Bulb2.mirror = true;
      setRotation(Bulb2, 0F, 0F, 0F);
      Bulb3 = new ModelRenderer(this, 0, 0);
      Bulb3.addBox(6F, 0.5F, -0.5F, 1, 1, 1);
      Bulb3.setRotationPoint(0F, 0F, 0F);
      Bulb3.setTextureSize(64, 32);
      Bulb3.mirror = true;
      setRotation(Bulb3, 0F, 0F, 0F);
      Bulb_4 = new ModelRenderer(this, 0, 0);
      Bulb_4.addBox(1F, 0.5F, 5.5F, 1, 1, 1);
      Bulb_4.setRotationPoint(0F, 0F, 0F);
      Bulb_4.setTextureSize(64, 32);
      Bulb_4.mirror = true;
      setRotation(Bulb_4, 0F, 0F, 0F);
      Bulb_5 = new ModelRenderer(this, 0, 0);
      Bulb_5.addBox(3.5F, 0.5F, 5.5F, 1, 1, 1);
      Bulb_5.setRotationPoint(0F, 0F, 0F);
      Bulb_5.setTextureSize(64, 32);
      Bulb_5.mirror = true;
      setRotation(Bulb_5, 0F, 0F, 0F);
      Bulb_6 = new ModelRenderer(this, 0, 0);
      Bulb_6.addBox(6F, 0.5F, 5.5F, 1, 1, 1);
      Bulb_6.setRotationPoint(0F, 0F, 0F);
      Bulb_6.setTextureSize(64, 32);
      Bulb_6.mirror = true;
      setRotation(Bulb_6, 0F, 0F, 0F);
      BaseBack = new ModelRenderer(this, 76, 0);
      BaseBack.addBox(-1F, 1F, 0F, 1, 6, 6);
      BaseBack.setRotationPoint(0F, 0F, 0F);
      BaseBack.setTextureSize(64, 32);
      BaseBack.mirror = true;
      setRotation(BaseBack, 0F, 0F, 0F);
      BasBottom = new ModelRenderer(this, 46, 0);
      BasBottom.addBox(1F, 6.5F, 1F, 11, 1, 4);
      BasBottom.setRotationPoint(0F, 0F, 0F);
      BasBottom.setTextureSize(64, 32);
      BasBottom.mirror = true;
      setRotation(BasBottom, 0F, 0F, 0F);
      bASEsIDE1 = new ModelRenderer(this, 52, 5);
      bASEsIDE1.addBox(0.5F, 2F, -0.7F, 11, 4, 1);
      bASEsIDE1.setRotationPoint(0F, 0F, 0F);
      bASEsIDE1.setTextureSize(64, 32);
      bASEsIDE1.mirror = true;
      setRotation(bASEsIDE1, 0F, 0F, 0F);
      bASEsIDE2 = new ModelRenderer(this, 52, 5);
      bASEsIDE2.addBox(0.5F, 2F, 5.7F, 11, 4, 1);
      bASEsIDE2.setRotationPoint(0F, 0F, 0F);
      bASEsIDE2.setTextureSize(64, 32);
      bASEsIDE2.mirror = true;
      setRotation(bASEsIDE2, 0F, 0F, 0F);
      hANDLEBASEFRONT = new ModelRenderer(this, 109, 13);
      hANDLEBASEFRONT.addBox(8F, -0.3F, -0.5F, 3, 3, 7);
      hANDLEBASEFRONT.setRotationPoint(0F, 0F, 0F);
      hANDLEBASEFRONT.setTextureSize(64, 32);
      hANDLEBASEFRONT.mirror = true;
      setRotation(hANDLEBASEFRONT, 0F, 0F, 0F);
      Handle = new ModelRenderer(this, 32, 0);
      Handle.addBox(1F, -5F, 2F, 2, 7, 2);
      Handle.setRotationPoint(0F, 0F, 0F);
      Handle.setTextureSize(64, 32);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0.3490659F);
      BlasterBit = new ModelRenderer(this, 20, 0);
      BlasterBit.addBox(12.7F, 1F, 0.5F, 1, 5, 5);
      BlasterBit.setRotationPoint(0F, 0F, 0F);
      BlasterBit.setTextureSize(64, 32);
      BlasterBit.mirror = true;
      setRotation(BlasterBit, 0F, 0F, 0F);
      Rod = new ModelRenderer(this, 19, 42);
      Rod.addBox(12F, 3F, 2.5F, 19, 1, 1);
      Rod.setRotationPoint(0F, 0F, 0F);
      Rod.setTextureSize(64, 32);
      Rod.mirror = true;
      setRotation(Rod, 0F, 0F, 0F);
      RodEnd1 = new ModelRenderer(this, 0, 24);
      RodEnd1.addBox(6F, 0F, -1F, 6, 1, 1);
      RodEnd1.setRotationPoint(30F, 3F, 4.5F);
      RodEnd1.setTextureSize(128, 64);
      RodEnd1.mirror = true;
      setRotation(RodEnd1, -0.7853982F, 0F, 0F);
      RodTerminus2 = new ModelRenderer(this, 0, 28);
      RodTerminus2.addBox(0F, -2F, -1F, 6, 2, 1);
      RodTerminus2.setRotationPoint(30F, 3F, 3F);
      RodTerminus2.setTextureSize(128, 64);
      RodTerminus2.mirror = true;
      setRotation(RodTerminus2, 0.7853982F, 0F, 0F);
      RodEnd3 = new ModelRenderer(this, 0, 24);
      RodEnd3.addBox(6F, 0F, -1F, 6, 1, 1);
      RodEnd3.setRotationPoint(30F, 5F, 2.5F);
      RodEnd3.setTextureSize(128, 64);
      RodEnd3.mirror = true;
      setRotation(RodEnd3, -3.141593F, 0F, 0F);
      RodEnd2 = new ModelRenderer(this, 0, 24);
      RodEnd2.addBox(6F, -1F, -1F, 6, 1, 1);
      RodEnd2.setRotationPoint(30F, 3F, 3F);
      RodEnd2.setTextureSize(128, 64);
      RodEnd2.mirror = true;
      setRotation(RodEnd2, 0.7853982F, 0F, 0F);
      RodTerminus1 = new ModelRenderer(this, 0, 28);
      RodTerminus1.addBox(0F, -1F, -1F, 6, 2, 1);
      RodTerminus1.setRotationPoint(30F, 3F, 4.5F);
      RodTerminus1.setTextureSize(128, 64);
      RodTerminus1.mirror = true;
      setRotation(RodTerminus1, -0.7853982F, 0F, 0F);
      RodTerminus3 = new ModelRenderer(this, 0, 28);
      RodTerminus3.addBox(0F, -1F, -1F, 6, 2, 1);
      RodTerminus3.setRotationPoint(30F, 5F, 2.5F);
      RodTerminus3.setTextureSize(128, 64);
      RodTerminus3.mirror = true;
      setRotation(RodTerminus3, -3.141593F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Bulb1.render(f5);
    Bulb2.render(f5);
    Bulb3.render(f5);
    Bulb_4.render(f5);
    Bulb_5.render(f5);
    Bulb_6.render(f5);
    BaseBack.render(f5);
    BasBottom.render(f5);
    bASEsIDE1.render(f5);
    bASEsIDE2.render(f5);
    hANDLEBASEFRONT.render(f5);
    Handle.render(f5);
    BlasterBit.render(f5);
    Rod.render(f5);
    RodEnd1.render(f5);
    RodTerminus2.render(f5);
    RodEnd3.render(f5);
    RodEnd2.render(f5);
    RodTerminus1.render(f5);
    RodTerminus3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void renderModel(float f5) {
    Base.render(f5);
    Bulb1.render(f5);
    Bulb2.render(f5);
    Bulb3.render(f5);
    Bulb_4.render(f5);
    Bulb_5.render(f5);
    Bulb_6.render(f5);
    BaseBack.render(f5);
    BasBottom.render(f5);
    bASEsIDE1.render(f5);
    bASEsIDE2.render(f5);
    hANDLEBASEFRONT.render(f5);
    Handle.render(f5);
    BlasterBit.render(f5);
    Rod.render(f5);
    RodEnd1.render(f5);
    RodTerminus2.render(f5);
    RodEnd3.render(f5);
    RodEnd2.render(f5);
    RodTerminus1.render(f5);
    RodTerminus3.render(f5);
  }
}
